### PR TITLE
CPedMovementDataNode

### PR DESCRIPTION
**Pull request by TheGreenBandit**
incomplete as its not mine, just saw it sometime this week and decided to grab it. would give credit to wherever i found it from but honestly I cannot remember

### CODE REVIEW

**Comment by SkiddyToast** [comment]
Gimme a couple minutes and I'll give you a better one to commit.

**Comment by TheGreenBandit** [comment]
where the hell u learn to do this shit anyway?

**Comment by SkiddyToast** [comment]
Lots of practice and looking at and comparing old GTA dumps.

**Comment by SkiddyToast** [comment]
```c++
#pragma pack(push,4)
class CPedMovementDataNode
{
public:
    char pad_0000[192]; //0x0000
    bool m_has_desired_move_blend_ratio_x; //0x00C0
    bool m_has_desired_move_blend_ratio_y; //0x00C1
    bool unk_00C2; //0x00C2
    float m_desired_move_blend_ratio_x; //0x00C4
    float m_desired_move_blend_ratio_y; //0x00C8
    float unk_00CC; //0x00CC
    float m_desired_pitch; //0x00D0
}; //Size: 0x00D4
static_assert(sizeof(CPedMovementDataNode) == 0xD4);
#pragma pack(pop)
```

**Comment by TheGreenBandit** [comment]
tell yimura on your guy's discord server to check this pr out

**Comment by Aure7138** [comment]
> tell yimura on your guy's discord server to check this pr out, also why is native_hooks in under src instead of being in the hook folder in yimmenu

I gotta say, it's kind of rude, just be patient

**Comment by TheGreenBandit** [comment]
> > tell yimura on your guy's discord server to check this pr out, also why is native_hooks in under src instead of being in the hook folder in yimmenu
> 
> I gotta say, it's kind of rude, just be patient

oh yeah i forgot what time it is lmao, i havent check the time in hours last i knew it was like 9pm for me

**Comment by Fuscina** [comment]
> ```c++
> #pragma pack(push,4)
> class CPedMovementDataNode
> {
> public:
>     char pad_0000[192]; //0x0000
>     bool m_has_desired_move_blend_ratio_x; //0x00C0
>     bool m_has_desired_move_blend_ratio_y; //0x00C1
>     bool unk_00C2; //0x00C2
>     float m_desired_move_blend_ratio_x; //0x00C4
>     float m_desired_move_blend_ratio_y; //0x00C8
>     float unk_00CC; //0x00CC
>     float m_desired_pitch; //0x00D0
> }; //Size: 0x00D4
> static_assert(sizeof(CPedMovementDataNode) == 0xD4);
> #pragma pack(pop)
> ```

This should be the full class, you can redo it in reclass but this is the names
```c++
class CPedMovementDataNode
{
public:
	virtual bool can_have_default_state();
	virtual bool has_default_state();
	virtual void set_default_state();
    bool m_has_desired_move_blend_ratio_x;
    bool m_has_desired_move_blend_ratio_y;
    bool m_has_stopped;
    float m_desired_move_blend_ratio_x;
    float m_desired_move_blend_ratio_y;
    float m_desired_pitch;
    float m_max_move_blend_ratio;
};```

**Comment by SkiddyToast** [comment]
> This should be the full class, you can redo it in reclass but this is the names
> 
> ```c++
> class CPedMovementDataNode
> {
> public:
>     virtual bool can_have_default_state();
>     virtual bool has_default_state();
>     virtual void set_default_state();
>     bool m_has_desired_move_blend_ratio_x;
>     bool m_has_desired_move_blend_ratio_y;
>     bool m_has_stopped;
>     float m_desired_move_blend_ratio_x;
>     float m_desired_move_blend_ratio_y;
>     float m_desired_pitch;
>     float m_max_move_blend_ratio;
> };
> ```

Are you sure they're in the right order? On the Xbox dump, `m_desired_pitch` is where your `m_max_move_blend_ratio` is.

This is what it looks like on the Xbox dump.
image
And on on 1.64 it looks like this, lining up with my struct:
image

**Comment by Fuscina** [comment]
> > This should be the full class, you can redo it in reclass but this is the names
> > ```c++
> > class CPedMovementDataNode
> > {
> > public:
> >     virtual bool can_have_default_state();
> >     virtual bool has_default_state();
> >     virtual void set_default_state();
> >     bool m_has_desired_move_blend_ratio_x;
> >     bool m_has_desired_move_blend_ratio_y;
> >     bool m_has_stopped;
> >     float m_desired_move_blend_ratio_x;
> >     float m_desired_move_blend_ratio_y;
> >     float m_desired_pitch;
> >     float m_max_move_blend_ratio;
> > };
> > ```
> 
> Are you sure they're in the right order? On the Xbox dump, `m_desired_pitch` is where your `m_max_move_blend_ratio` is.
> 
> This is what it looks like on the Xbox dump. image And on on 1.64 it looks like this, lining up with my struct: image

Ye its different on the pc build

**Comment by SkiddyToast** [comment]
> Ye its different on the pc build

I don't see how it's different...

**Comment by Fuscina** [comment]
> > Ye its different on the pc build
> 
> I don't see how it's different...

My bad im running on empty rn and forgot the padding, the virtual functions names maybe be wrong but i guessed on what they do
```c++
class CPedMovementDataNode
{
public:
       virtual bool can_have_default_state();
       virtual bool has_default_state();
       virtual void set_default_state();
    
	char pad_0000[192]; //0x0000
	bool m_has_desired_move_blend_ratio_x; //0x00C0
	bool m_has_desired_move_blend_ratio_y; //0x00C1
	bool m_has_stopped; //0x00C2
	float m_desired_move_blend_ratio_x; //0x00C3
	float m_desired_move_blend_ratio_y; //0x00C7
	float m_desired_pitch; //0x00CB
	float m_max_move_blend_ratio; //0x00CF
}; //Size: 0x00D3
```

**Comment by TheGreenBandit** [comment]
theres a CPedOrientationDataNode idk where to get it but I've heard of it, if its found we can add to this commit

**Comment by TheGreenBandit** [comment]
found something else i have lying around, probably not finished too

**Comment by Hydra-Source** [comment]
> found something else i have lying around, probably not finished too

Why are you commiting someone elses work? Did you get permission to? Doesn't make any sense to me.

**Comment by TheGreenBandit** [comment]
as i said before i dont remember where i found it from, as i had them lying around on my pc. saw the vehicle datanode i had was not in yim classes so i decided to push it, i dont take credit for any of these classes, i just think its best to push the classes so that more people know about and can use them

**Comment by Hydra-Source** [comment]
> > Why are you comiting someone elses work? Did you get permission to? Doesn't make any sense to me.
> 
> as i said before i dont remember where i found it from, as i had them lying around on my pc. saw the vehicle datanode i had was not in yim classes so i decided to push it, i dont take credit for any of these classes, i just think its best to push the classes so that more people know about and can use them

I know where you found them. But thats another story. Secondly none of the classes nor members were correct.

**Comment by TheGreenBandit** [comment]
> > > Why are you comiting someone elses work? Did you get permission to? Doesn't make any sense to me.
> > 
> > 
> > as i said before i dont remember where i found it from, as i had them lying around on my pc. saw the vehicle datanode i had was not in yim classes so i decided to push it, i dont take credit for any of these classes, i just think its best to push the classes so that more people know about and can use them
> 
> I know where you found them. But thats another story. Secondly none of the classes nor members were correct.

ok? as i said i just wanna get the classes out there so more people can use them

**Comment by Yimura** [comment]
> ok? as i said i just wanna get the classes out there so more people can use them

Let's try focussing on the original title of this PR `CPedMovementDataNode`.
Posting an incomplete/unusable class will not really help anyone currently, if you do not have the capabilities to research it more then don't add it.

Moving on please remove the file with the `CVehicleControlDataNode` class, that way if the `CPedMovementDataNode` class is ready we can merge that one in already.

In general try to make a PR a single feature thing and not something that remains open while you scramble to add small bits of incomplete information. This causes the PR to stall and remain open for longer while some people might have already been able to make use of it.

**Comment by Hydra-Source** [comment]
> > I know where you found them. But thats another story. Secondly none of the classes nor members were correct.
> 
> 
> 
> ok? as i said i just wanna get the classes out there so more people can use them

I know you just want to help. But if you don't understand the basic concept of classes and creating them. You should focus on helping people another way. Your way.

**Comment by TheGreenBandit** [comment]
Just realized where  i got the code from, from a menu called atomic that the owner himself leaked on discord.

**Comment by Dan199624** [comment]
would be nice to have some credits :(

**Comment by Yimura** [comment]
> would be nice to have some credits :(

Credit for what? I know @TheGreenBandit used some leaked class which is not allowed, then @SkiddyToast went and reversed it himself making so there's no need to ask permission of the original code owner.

**Comment by Dan199624** [comment]
guess whos the original owner

**Comment by SkiddyToast** [comment]
> guess whos the original owner

Rockstar.

**Comment by Dan199624** [comment]
> > guess whos the original owner
> 
> Rockstar.

also the orientation node he said he heard of. the only reason he heard of it was because i kept the file but removed the hook and class lol

**Comment by Yimura** [comment]
> also the orientation node he said he heard of. the only reason he heard of it was because i kept the file but removed the hook and class lol

A vtable name is not a secret they're all on FiveM repo.

**Comment by SkiddyToast** [comment]
> also the orientation node he said he heard of. the only reason he heard of it was because i kept the file but removed the hook and class lol

I’ve had that node mapped out for a long time, it’s sitting on my IDA lol

**Comment by Dan199624** [comment]
> > also the orientation node he said he heard of. the only reason he heard of it was because i kept the file but removed the hook and class lol
> 
> A vtable name is not a secret they're all on the FiveM repo.

just saying where he got it from

**Comment by Yimura** [comment]
> just saying where he got it from

I've checked your Github account and indeed you've got something there that is the Atomic source of some sorts, it doesn't have a license so in no standpoint was TheGreenBandit allowed to use it and neither are we allowed to put it in GTAV-Classes.
We (SkiddyToast) has since posted his own reversal version of the class thus removing any need to give credits or giving us any licensing problems on that part.

**Pull request merged**
