### PR TITLE
Add InputMethodEditor

### PR DESCRIPTION
**Pull request by Mr-X-GTA**

### CODE REVIEW

**Review by gir489returns — CHANGES_REQUESTED** [review]
You also need to include this into classes.cpp and then make sure it builds.

**Review by gir489returns — APPROVED** [review]
It's failing on linux for reason I do not care.

**Comment by Yimura** [comment]
The static_assertion works on MSVC but not on gcc? Weird...

**Comment by gir489returns** [comment]
> Because wchar_t is 4 bytes on Linux

Could probably fix that with allignas(8)

**Comment by Yimura** [comment]
Is this really the first PR with wchar_t?

**Comment by xiaoxiao921** [comment]
GTA is a MSVC compiled game for Windows, why is there even a CI for linux?

**Comment by Yimura** [comment]
Ahaha, previously I used char16_t

https://github.com/Yimura/GTAV-Classes/blob/21cbc2076b8d0ac9cbd98d05ebabadcced546f30/network/ChatData.hpp#L20

**Comment by gir489returns** [comment]
> GTA is a MSVC compiled game for Windows, why is there even a CI for linux?

Because linuxcucks complained that they can't compile it without using MSVC.

**Comment by Yimura** [comment]
> GTA is a MSVC compiled game for Windows, why is there even a CI for linux?

External linux cheat support.

**Comment by xiaoxiao921** [comment]
> > GTA is a MSVC compiled game for Windows, why is there even a CI for linux?
> 
> Because linuxcucks complained that they can't compile it without using MSVC.

YimMenu is fully compilable with this package https://aur.archlinux.org/packages/msvc-wine-git

I propose removing the linux CI.

**Comment by gir489returns** [comment]
> I propose removing the linux CI.

Agreed.

**Pull request merged**
