### PR TITLE
Add global classes

### PR DESCRIPTION
**Pull request by maybegreat48**
I have no clue how I'm going to update this

### CODE REVIEW

**Comment by TheGreenBandit** [comment]
how do u even find things like this? like is there a youtube video or online guide that i could follow to learn?

**Review by Yimura — APPROVED** [review]
Excellent work as always.

**Comment by MoneyDropLobby** [comment]
how the heck do you want to update these? Isn't it easier to work with the global index?

**Comment by MoneyDropLobby** [comment]
I also have some globals to add but I can't figure out how the class work

**Comment by TheGreenBandit** [comment]
> I also have some globals to add but I can't figure out how the class work

what are u trying top add, open up a pr paste the code in a file and i'll sort it for u

**Pull request merged**
