### PR TITLE
ClanData misalignment fix in CNetGamePlayer.hpp

### PR DESCRIPTION
**Pull request by ScottiePimp**
m_clan_data was misaligned by 16 bytes.

### CODE REVIEW

**Comment by gir489returns** [comment]
Are you sure this is correct?

**Comment by ScottiePimp** [comment]
I'm pretty sure I use the same classes as Yimura from 1.67, Haven't made any personal changes, just noticed that ClanData was off by 16 bytes for me. I'll take a second look give me a second.

**Comment by gir489returns** [comment]
image


You can clearly see the other data has shifted as well.

**Comment by ScottiePimp** [comment]
Weird.. even though my classes are pretty much identical to Yimura right now it's still off by 16 bytes. I'll check ReClass and go over everything one more time after work.

**Comment by gir489returns** [comment]
@ScottiePimp did you ever get around to checking this?

**Comment by ScottiePimp** [comment]
> @ScottiePimp did you ever get around to checking this?

Oh right, I've been real busy with work haven't had the time. All I really did was double check my classes' allignment, nothing seemed out of the ordinary so I kinda dropped it. But if those normal offsets work for you, something is definitely wrong so I can take a look in ReClass when I have some freetime.

**Comment by gir489returns** [comment]
@ScottiePimp Were you able to verify the padding?

**Comment by Yimura** [comment]
Stale

**Pull request closed without merging**
