### PR TITLE
feat(CreationDataNodes): Add more creation data nodes.

### PR DESCRIPTION
**Pull request by SkiddyToast**
IDK how there's 11 commits, if someone knows how to fix this then please tell me lmao.

### CODE REVIEW

**Comment by xM4ddy** [comment]
Doesn't really matter whoever reviews it can just squash and merge if you meant to have all of these commits. If not you should make a separate branch for PRs and push to those to fix this you can use revert or reset to go back commits if that's what you want or something.

**Comment by Yimura** [comment]
Those old commits being there can't really be resolved, you probably need to delete your repository and fork it again to start of fresh.

**Comment by xiaoxiao921** [comment]
As an alternative, you can start a fresh branch synced with upstream and just cherry pick the commits you need

**Review by Yimura — APPROVED** [review]

**Comment by Yimura** [comment]
@SkiddyToast is it possible you forgot pragma pack for the other classes or do they work without modifying their pack size?

**Comment by SkiddyToast** [comment]
AFAIK, they work, IDA didn't specify any packing on them.

**Pull request merged**
