### PR TITLE
Adding New Classes

### PR DESCRIPTION
**Pull request by MoneyWasted**
Added New Previously Unknown Classes and Enums.
Wrote a Simple Batch Script to Generate the `classes.cpp` File.

### CODE REVIEW

**Comment by secret-stash** [comment]
I think I've never seen such a great reverse engineer before. Truly exceptional talent.

**Comment by brunph** [comment]
Please redo the pull request with padding on the classes, it exists for a reason.

**Comment by yubie-re** [comment]
least copyright infringing yim commit

**Comment by Kryo77** [comment]
Pointless PR, you can't just paste stuff from the leaked pdb and expect it to work.

**Comment by Yimura** [comment]
Love it when people just add stuff that they clearly got through illegitimate means.

**Pull request closed without merging**
